language: node_js
node_js:
- "10"
before_script:
 - npm install -g firebase-tools
 - npm install
script:
 - npm test
after_success:
 - firebase deploy --token $FIREBASE_TOKEN --non-interactive
notifications:
 email:
  recipients:
   - lariel.negreiros@gmail.com
on_success: change # default: change
on_failure: always # default: always 